version: '3'

env:
  IMAGE_BUILDER: podman

includes:
  kind:
    taskfile: ./deployments/kind
    dir: ./deployments/kind


tasks:
  helmfile:apply:
    desc: "Apply helmfile.yaml"
    cmds:
    - helmfile apply
  argo:bootstrap:
    desc: "Bootstrap ArgoCD - Install App of Apps"
    cmds:
    - kubectl apply -f deployments/kubernetes/bootstrap/manifest.yaml
  image:build:
    desc: "Build image"
    cmds:
    - $IMAGE_BUILDER build -f build/package/Dockerfile .
    silent: true
