apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: integration
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: deployments/kubernetes/integration
    repoURL: 'git@github.com:RobKenis/workshop-kubernetes-gitops.git'
    targetRevision: main
    kustomize:
      namespace: integration
      patches:
      - target:
          kind: Namespace
        patch: |-
          - op: replace
            path: /metadata/name
            value: integration
      - target:
          kind: Ingress
        patch: |-
          - op: replace
            path: /spec/rules/0/host
            value: integration.sandbox-2024.axxes.cloud
          - op: replace
            path: /spec/tls/0/hosts/0
            value: integration.sandbox-2024.axxes.cloud
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
