apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../application

patches:
- target:
    kind: Namespace
  patch: |-
    - op: replace
      path: /metadata/name
      value: integration
