Description: 'EKS Cluster for GitOps workshop'
Parameters:
  ClusterName:
    Type: String
    Default: 'gitops-workshop'
    Description: 'Name of the EKS cluster'
  ControlPlaneSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: 'Subnets for the EKS control plane'
Resources:
  ManagementRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
          Action: "sts:AssumeRole"
  Cluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      Version: "1.31"
      RoleArn: !GetAtt ManagementRole.Arn
      ResourcesVpcConfig:
        EndpointPublicAccess: true
        SubnetIds: !Ref ControlPlaneSubnets
      Tags:
      - Key: "Project"
        Value: "git@github.com:RobKenis/workshop-kubernetes-gitops.git"
