apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-nodes
  namespace: argocd
spec:
  destination:
    namespace: karpenter
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployments/kubernetes/karpenter-nodes
    repoURL: 'git@github.com:RobKenis/workshop-kubernetes-gitops.git'
    targetRevision: main
    kustomize:
      patches:
      - target:
          kind: EC2NodeClass
        patch: |-
          - op: add
            path: /spec/role
            value: Karpenter-workshop-gitops-2024111506365272240000001b
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
