apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- karpenter.yaml
- karpenter-nodes/
- integration.yaml

patches:
- target:
    kind: Application
  patch: |-
    - op: add
      path: /metadata/finalizers
      value: [ resources-finalizer.argocd.argoproj.io ]
