apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- karpenter.yaml
- karpernter-nodes.yaml
- integration.yaml
- integration-generator.yaml
- load-balancer-controller.yaml
- external-dns.yaml

patches:
- target:
    kind: Application
  patch: |-
    - op: add
      path: /metadata/finalizers
      value: [ resources-finalizer.argocd.argoproj.io ]
